[build]
publish = "public"
command = "npm run build"
functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions."supabase-heartbeat"]
  schedule = "0 5 * * 1,4"
